---

 - name: NGINX Install and Configure
   hosts: all
   become: true


   vars:
    nginx_listen_port:  8080
    jinja2_src_dir: /home/vagrant/ansible
    nginx_cfg_dir: /etc/nginx

   tasks:
     - name: update
       ansible.builtin.apt:
        update_cache=yes
       tags:
        - update apt
       when: ansible_os_family == "Debian" 

     - name: NGINX Install
       ansible.builtin.package: name=nginx state=latest 
       notify:
        - restart nginx
       tags:
        - nginx-package

     - name: NGINX Service
       ansible.builtin.service: name=nginx state=started enabled=yes


     - name: NGINX Create config from jinja2 template
       ansible.builtin.template:
         src: "{{ jinja2_src_dir }}/nginx.conf.j2"
         dest: "{{ nginx_cfg_dir }}/nginx.conf"
         mode: 0555
       notify: 
         - reload nginx
       tags:
         -nginx-configuration

     - name: NGINX Firewall oprts
       ansible.posix.firewalld:
        port: 8080/tcp
        permanent: true
        state: enabled
       notify: restart firewalld 
       when: ansible_os_family == "RedHat"



   handlers:
        - name: restart nginx
          ansible.builtin.service: name=nginx state=restarted

        - name: reload nginx
          ansible.builtin.service: name=nginx state=reloaded

        - name: restart firewalld
          ansible.builtin.service: name=firewalld state=restarted  
