#BOX = "ubuntu/jammy64"
#BOX_Ver = "20240426.0.0"

BOX = "generic/centos8s"
BOX_Ver = "4.3.12"

#BOX = "ilionx/ubuntu2204"
#BOX_Ver = "1.5.0-20240320"

#BOX = "virusstyle/ubuntu-22.04-desktop-amd64"
#BOX_Ver = "1.0.0"

VM_GUEST_PORT = 22
VM_HOST_PORT = 2245

home = ENV['HOME']

VAGRANT_DISABLE_VBOXSYMLINKCREATE=1  #disable sinlinks https://www.virtualbox.org/manual/ch04.html#sharedfolders

Vagrant.require_version ">= 1.3.5"

Vagrant.configure("2") do |config|

  config.vm.define "VBOX-CENTOS-NESTED" do |ct| 
    ct.vm.box = BOX
    ct.vm.box_version = BOX_Ver
    #ct.vm.network "public_network", bridge: "Realtek PCIe GbE Family Controller", use_dhcp_assigned_default_route: true
    #ct.vm.network "public_network", bridge: "Realtek PCIe GbE Family Controller", auto_config: false
    ct.vm.network "forwarded_port", guest: VM_GUEST_PORT, host: VM_HOST_PORT 
    #ct.vm.network "private_network", :type => 'dhcp' 
    ct.vm.box_check_update = false
    ct.vm.hostname = "centos8-nested.vagrant"
    ct.ssh.insert_key = false
    #ct.vm.define "vbox-centos8-nested"
    ct.vm.disk :disk, size: "20GB", primary: true
    ct.vm.synced_folder "/tmp/vagrant/machine1", "/home/vagrant/machine1", SharedFoldersEnableSymlinksCreate: false #, type: "smb"
    ct.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 1
      vb.name = "vbox-centos8-nested"
      #vb.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
      vb.customize ["modifyvm", :id, "--audio", "none"]

    end
  #shell inline provision
    ct.vm.provision "shell",  inline: <<-SHELL
      #sudo ip address add 10.0.2.25/24 brd 10.0.2.255 dev enp0s3
      #sudo ip route add default via 10.0.2.1
      #sudo apt-get update
      #sudo apt full-upgrade --assume-yes
      #sudo apt-get install -y apache2 
    SHELL
 

  #shell file script provision
    #jd.vm.provision "shell", path: "script.sh" 
   


  #jd.vm.provision "ansible" do |ansible|
  #      ansible.playbook = "site.yml"
  #      ansible.verbose = "vv"  
  #end


   end
end

